#ifndef MCAL_INTERRUPT_GEN_CFG_H_
#define MCAL_INTERRUPT_GEN_CFG_H_

#define INTERRUPT_FEATURE_ENABLE        1
#define INTERRUPT_FEATURE_DISABLE       0
#define INTERRUPT_PRIORITY_LEVELS_ENABLE    INTERRUPT_FEATURE_DISABLE

#define EXTERNAL_INTERRUPT_INTx_ENABLE      INTERRUPT_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_OnChange_ENABLE  INTERRUPT_FEATURE_ENABLE


#endif /* MCAL_INTERRUPT_GEN_CFG_H_ */